### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'lora_dir'

### ISSUE THREAD

**Issue by Yakonche** [DominikDoom/a1111-sd-webui-tagcomplete#119]
Hi, i've got this problem when i launch webui-user.bat :

```
remote: Enumerating objects: 405, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 405 (delta 238), reused 247 (delta 223), pack-reused 124
Receiving objects: 100% (405/405), 164.08 KiB | 7.81 MiB/s, done.
Resolving deltas: 100% (279/279), completed with 54 local objects.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
   ce72af8..226d840  master     -> origin/master
 * [new branch]      lora_sd2   -> origin/lora_sd2
error: Your local changes to the following files would be overwritten by merge:
        style.css
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        modules/ui_common.py
        modules/ui_extra_networks.py
        modules/ui_extra_networks_hypernets.py
        modules/ui_extra_networks_textual_inversion.py
        modules/ui_postprocessing.py
        scripts/xyz_grid.py
Please move or remove them before you merge.
Aborting
Updating b165e34..226d840
venv "C:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Commit hash: b165e341e70300f66c8a77b9383041f4147b24a8
Installing requirements for Web UI
Installing requirements for Anime Background Remover
Installing requirements for Anime Background Remover
Installing requirements for Anime Background Remover



loading Smart Crop reqs from C:\stable-diffusion-webui\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.


Launching Web UI with arguments: --no-half --medvram --theme=dark --autolaunch --xformers --gradio-img2img-tool color-sketch --gradio-inpaint-tool color-sketch --allow-code
**Error loading script: tag_autocomplete_helper.py**
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 23, in <module>
    LORA_PATH = Path(shared.cmd_opts.lora_dir)
**AttributeError: 'Namespace' object has no attribute 'lora_dir'**

Loading config from: C:\stable-diffusion-webui\models\Stable-diffusion\StableDiffusion2.1.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [4a408d2491] from C:\stable-diffusion-webui\models\Stable-diffusion\StableDiffusion2.1.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 11.7s (0.3s create model, 8.7s load weights).
[tag-editor] Settings has been read from config.json
Error executing callback ui_tabs_callback for C:\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 105, in ui_tabs_callback
    res += c.callback() or []
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 420, in on_ui_tabs
    create_tab(tab)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-instruct-pix2pix\scripts\instruct-pix2pix.py", line 254, in create_tab
    ip2p_prompt, ip2p_prompt_styles, ip2p_negative_prompt, submit, ip2p_interrogate, ip2p_deepbooru, ip2p_prompt_style_apply, ip2p_save_style, ip2p_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=True)
ValueError: not enough values to unpack (expected 14, got 11)

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 2] The specified file can not be found: 'C:\\stable-diffusion-webui\\extensions\\a1111-sd-webui-tagcomplete\\tags\\temp\\hyp.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path C:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\tags\temp\hyp.txt does not exist.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\starlette\responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 2] The specified file can not be found: 'C:\\stable-diffusion-webui\\extensions\\a1111-sd-webui-tagcomplete\\tags\\temp\\hyp.txt'
```

Here is my webui-user.bat :

```
@echo off

set SAFETENSORS_FAST_GPU=1
set TORCH_CUDA_ARCH_LIST=6.1

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--no-half --medvram --theme=dark --autolaunch --xformers --gradio-img2img-tool color-sketch --gradio-inpaint-tool color-sketch --allow-code

:: set "REQS_FILE=.\extensions\sd_dreambooth_extension\requirements.txt"
:: set "DREAMBOOTH_SKIP_INSTALL=True"
git pull
:: set ACCELERATE="True"

call webui.bat
```

I have no idea where the problem could come from.

**Comment by DominikDoom** [comment]
Your webui is too old for the current version of tag aucocomplete. You are on commit b165e341e70300f66c8a77b9383041f4147b24a8, which is from 2 weeks ago. Lora support (including the lora_dir attribute) were added a few commits after.

Have a look at the first few lines of your output:
```
remote: Enumerating objects: 405, done.
remote: Counting objects: 100% (281/281), done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 405 (delta 238), reused 247 (delta 223), pack-reused 124
Receiving objects: 100% (405/405), 164.08 KiB | 7.81 MiB/s, done.
Resolving deltas: 100% (279/279), completed with 54 local objects.
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
   ce72af8..226d840  master     -> origin/master
 * [new branch]      lora_sd2   -> origin/lora_sd2
error: Your local changes to the following files would be overwritten by merge:
        style.css
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
        modules/ui_common.py
        modules/ui_extra_networks.py
        modules/ui_extra_networks_hypernets.py
        modules/ui_extra_networks_textual_inversion.py
        modules/ui_postprocessing.py
        scripts/xyz_grid.py
Please move or remove them before you merge.
Aborting
Updating b165e34..226d840
```

That says it can't update because you have local changes that would be overridden.
So you'd have to revert them, or stash if you want to keep them:
```cmd
git stash
git pull
git stash pop
```
Should stash your changes, pull, and reapply them after.

**Comment by Yakonche** [comment]
I've got this message :

```
PS C:\stable-diffusion-webui> git stash
Saved working directory and index state WIP on master: b165e34 Merge pull request #6930 from poiuty/master
PS C:\stable-diffusion-webui> pit pull
pit : Le terme «pit» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez
l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ pit pull
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\stable-diffusion-webui> git pull
error: The following untracked working tree files would be overwritten by merge:
        modules/ui_common.py
        modules/ui_extra_networks.py
        modules/ui_extra_networks_hypernets.py
        modules/ui_extra_networks_textual_inversion.py
        modules/ui_postprocessing.py
        scripts/xyz_grid.py
Please move or remove them before you merge.
Aborting
Updating b165e34..226d840
PS C:\stable-diffusion-webui> git pull --force
error: The following untracked working tree files would be overwritten by merge:
        modules/ui_common.py
        modules/ui_extra_networks.py
        modules/ui_extra_networks_hypernets.py
        modules/ui_extra_networks_textual_inversion.py
        modules/ui_postprocessing.py
        scripts/xyz_grid.py
Please move or remove them before you merge.
Aborting
Updating b165e34..226d840
PS C:\stable-diffusion-webui> git stash pop
On branch master
Your branch is behind 'origin/master' by 252 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    extensions/put extensions here.txt
        deleted:    models/Stable-diffusion/Put Stable Diffusion checkpoints here.txt
        deleted:    screenshot.png
        modified:   style.css
        deleted:    webui-macos-env.sh
        modified:   webui-user.bat
        deleted:    webui-user.sh
        deleted:    webui.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        BasicTestUpscalewChaiNNer.chn
        NegativePrompt.txt
        modules/modules/
        modules/ui_common.py
        modules/ui_extra_networks.py
        modules/ui_extra_networks_hypernets.py
        modules/ui_extra_networks_textual_inversion.py
        modules/ui_postprocessing.py
        scripts/vue.min.js
        scripts/xyz_grid.py
        scripts/xyz_grid.template.html
        xor_pass.txt

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (003b8970ff83f2144a7fad37be7881e5136bd317)
PS C:\stable-diffusion-webui>
```

**Comment by DominikDoom** [comment]
Hm, it seems like you have some local untracked files that also exist on the origin.

A few options:
Add your local files, overwrite them, then reapply your changes:
```
git add -A .
git stash
git pull
git stash pop
```
Hard reset:
```
git stash
git reset --hard origin/master
git pull
git stash pop
```

If you don't want to keep local changes, you can do it without the stash:
```
git reset --hard origin/master
git pull
```
But keep in mind that this will also remove stuff like your user-bat modifications and additional files

if even that doesn't work:
```
git clean -n -f -d
```
will show you what would be removed, running the same command without -n will then remove it for real.

Or doing it manually, move out all files you want to keep modifications for, hard reset, move them back in.

**Comment by DominikDoom** [comment]
I've added a catch for the exception itself, so it should now also work with older versions without errors.
But this will of course not fix the root of the problem for which the newer versions are needed, so I'd still recommend you clean your webui installation up so git pull can update without issues again.

**Comment by CCpt5** [comment]
I think my error is very similar to this one. I do use an old version of the webui as a few features I rely on are broken in the most recent commits. I have updated your extension to the latest commit, and also tried checking out bb82f20 but still get the following error:


```
Launching Web UI with arguments: --xformers --api --ckpt-dir e:\Stable Diffusion Checkpoints
Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 237, in <module>
    if LORA_PATH.exists():
AttributeError: 'NoneType' object has no attribute 'exists'
```

I really like the extension, and I'm not sure how I broke it as it was working earlier today. I did run an update all extensions and had been using dynamic prompts magic prompts+wildcards - so perhaps something there caused it. 

If the only real solution is to upgrade to the latest version of the A1111 I understand. Thanks for any insight.

**Comment by DominikDoom** [comment]
@CCpt5 Ah no, that just looks like my safety catch was incomplete. Sorry for the inconvenience, I'll fix it in a bit.

**Comment by CCpt5** [comment]
I can't check it myself until the morning, but I'm sure it's good. Thank you so much for all of your efforts! Really love the extension.
