### ISSUE TITLE
Sudden fail of the extension, after updating other extensions.

### ISSUE THREAD

**Issue by mart-hill** [DominikDoom/a1111-sd-webui-tagcomplete#121]
After I updated `dreambooth`, `pix2pix`, `UmiAI `and `additional-networks`, **tagcomplete** started throwing this error:

```
Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "O:\AI\stable-diffusion-webui\modules\scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "O:\AI\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "O:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 217, in <module>
    wildcards_yaml_ext = get_ext_wildcard_tags()
  File "O:\AI\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 74, in get_ext_wildcard_tags
    wildcard_tags[count] = ','.join(data[item]['Tags'])
TypeError: 'NoneType' object is not subscriptable
```

It probably has to do something with WebUI failing to run after these 4 extensions were updated (I'm on 226d840e84c5f306350b0681945989b86760e616 WebUI commit, latest at the moment) - I had errors immediately after fully re-running the UI. So I upgraded `pip` in venv (new version just appeared), and also disabled `--skip-version-check` in the UI's .bat file, since I think one of these four extensions required something newer. It worked, WebUI started working again, but your extension now is having trouble. 

Since you explained me the severity of that option at the time - I didn't touch tagcomplete options, it was normally working, until I restarted the UI.
Should I edit some setting again?

I hope I explained it fairly well... 🙂

**Comment by MrGrey7** [comment]
Can confirm, I get the same error after updating installing UmiAI and updating pix2pix

**Comment by mart-hill** [comment]
Thank you, it seems to even pinpoint the "culprit"! 🙂
