### ISSUE TITLE
Error loading script: model_keyword_support.py and error loading script: tag_autocomplete_helper.py

### ISSUE THREAD

**Issue by Some1StoleMyName** [DominikDoom/a1111-sd-webui-tagcomplete#203]
im getting this error

*** Error loading script: model_keyword_support.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\model_keyword_support.py", line 10, in <module>
        known_hashes_file.touch()
      File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1168, in touch
        self._accessor.touch(self, mode, exist_ok)
      File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 331, in touch
        fd = os.open(path, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion-webui\\extensions\\a1111-sd-webui-tagcomplete\\tags\\temp\\known_lora_hashes.txt'

---
*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 11, in <module>
        from scripts.model_keyword_support import (get_lora_simple_hash,
      File "D:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\model_keyword_support.py", line 10, in <module>
        known_hashes_file.touch()
      File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1168, in touch
        self._accessor.touch(self, mode, exist_ok)
      File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 331, in touch
        fd = os.open(path, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable-diffusion-webui\\extensions\\a1111-sd-webui-tagcomplete\\tags\\temp\\known_lora_hashes.txt'

**Comment by changaolee** [comment]
same error

**Comment by Therises** [comment]
Same here.

**Comment by DominikDoom** [comment]
This was due to not checking if the temp folder itself was already created at this point.
I only tested it with an existing installation and the files itself being deleted, not the whole folder, so I didn't catch it. Sorry for the inconvenience.
