### ISSUE TITLE
Error on Hotfix 2.7.2

### ISSUE THREAD

**Issue by clownmoney** [DominikDoom/a1111-sd-webui-tagcomplete#204]
Just pulled because of the [previous error](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/203) which was already taken care of. I now have another error.

```
*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "C:\Users\user\OneDrive\Documents\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\user\OneDrive\Documents\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\user\OneDrive\Documents\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 284, in <module>
        write_temp_files()
      File "C:\Users\user\OneDrive\Documents\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 264, in write_temp_files
        load_hash_cache()
      File "C:\Users\user\OneDrive\Documents\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\model_keyword_support.py", line 21, in load_hash_cache
        for line in file:
      File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5609: character maps to <undefined>

---
```

**Comment by DominikDoom** [comment]
Huh, I thought I already fixed that in #202. Now it should work for sure though, no other file read/write related stuff left :D
