### ISSUE TITLE
Directory named `.safetensors`  causes model-keyword to break and to break `webui-tagcomplete` in return

### ISSUE THREAD

**Issue by ivucica** [DominikDoom/a1111-sd-webui-tagcomplete#251]
When the only extensions installed are `model-keyword` and `a1111-sd-webui-tagcomplete` (all others being moved away), and when `config.json` has also been moved away, then an attempt to open a directory that happens to have a `.safetensors` "extension" fails and completely breaks the startup of the extension:

```
*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 326, in <module>
        write_temp_files()
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 310, in write_temp_files
        lora = get_lora()
               ^^^^^^^^^^
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 186, in get_lora
        hashes[name] = get_lora_simple_hash(l)
                       ^^^^^^^^^^^^^^^^^^^^^^^
      File "/mnt/aiart/stable-diffusion/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/model_keyword_support.py", line 48, in get_lora_simple_hash
        with open(path, "rb") as file:
             ^^^^^^^^^^^^^^^^
    IsADirectoryError: [Errno 21] Is a directory: '/mnt/aiart/stable-diffusion/stable-diffusion-webui/models/Lora/31817-xsarchitectural-19Houseplan.safetensors'

```

The extension does not load and its options do not appear in `Settings` of a1111.

This also causes #250.

**Comment by DominikDoom** [comment]
Fixed by adding a filter condition that the found path actually is a file. This would've likely also affected all other places where the extension searches for specific file types, so pretty much everything except embeddings. Good catch!
This should also fix #250 since that likely was only a symptom, feel free to reopen that if it is something else.
