### ISSUE TITLE
Extention Not Working At All | Not loading modules

### ISSUE THREAD

**Issue by andy8992** [DominikDoom/a1111-sd-webui-tagcomplete#300]
During startup

*** Error loading script: model_keyword_support.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\a1111-sd-webui-tagcomplete\scripts\model_keyword_support.py", line 7, in <module>
        from scripts.shared_paths import EXT_PATH, STATIC_TEMP_PATH, TEMP_PATH
    ModuleNotFoundError: No module named 'scripts.shared_paths'

---
*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 19, in <module>
        from scripts.model_keyword_support import (get_lora_simple_hash,
    ModuleNotFoundError: No module named 'scripts.model_keyword_support'

---
*** Error loading script: tag_frequency_db.py
    Traceback (most recent call last):
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 525, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Data\Packages\Stable Diffusion WebUI Forge\extensions\a1111-sd-webui-tagcomplete\scripts\tag_frequency_db.py", line 4, in <module>
        from scripts.shared_paths import TAGS_PATH
    ModuleNotFoundError: No module named 'scripts.shared_paths'

**Comment by DominikDoom** [comment]
Update your forge version, this is a bug introduced on their side that's been fixed for a while.

Duplicate of #299

**Comment by andy8992** [comment]
Okay, I updated it today and still am getting this error. I've tried reinstalling manually and in the UI.

**Comment by DominikDoom** [comment]
Does the proposed fix from the linked issue work for you? Try creating an empty file named `__init__.py` (two underscores on both sides) in TAC's scripts directory.

Otherwise, I think just updating forge might not be enough, since the root cause was a broken gguf dependency. You might need to recreate your venv to properly clean the error.

**Comment by DominikDoom** [comment]
That's still the same issue just for a different import, these are all local scripts in the same folder that should be found no matter what. So I guess fixing the venv as quoted in my last comment is the only thing left to try.

**Comment by andy8992** [comment]
> That's still the same issue just for a different import, these are all local scripts in the same folder that should be found no matter what. So I guess fixing the venv as quoted in my last comment is the only thing left to try.

Giving that a shot now. Dang things 7gb I guess. Dumb rural internet heh.

Thanks, I'll let you know

**Comment by andy8992** [comment]
Unfortunately that didn't seem to help. Bummer

**Comment by andy8992** [comment]
WAIT! I think I got it, I downloaded the older commit, the one from the releases from Feb and I think maybe i didn't put __init__.py in the scripts folder rather than the main one. Thanks for your help.

**Comment by DominikDoom** [comment]
Wait, so just for clarification, it only works with an older release of TAC? That would not be ideal, as there've been a lot of additions (and also forge-specific fixes) since then.
