### ISSUE TITLE
YAML file misinterpreted as wildcard (TypeError: list indices must be integers or slices, not dict)

### ISSUE THREAD

**Issue by faustoserone** [DominikDoom/a1111-sd-webui-tagcomplete#308]
Hi,
I haven't used A1111 for a couple of months.
Today I updated it and I got the following error:

*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 535, in <module>
        write_temp_files()
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 505, in write_temp_files
        get_yaml_wildcards()
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 180, in get_yaml_wildcards
        if (is_umi_format(data)):
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 137, in is_umi_format
        if not (data[item] and 'Tags' in data[item] and isinstance(data[item]['Tags'], list)):
    TypeError: list indices must be integers or slices, not dict

can you help me please? thank you.

**Comment by DominikDoom** [comment]
It seems you have a YAML file somewhere that TAC thinks is a specific format of wildcard list but fails to parse it as such (likely located in another extension). Normally it should already ignore errors that happen there, but it seems this failed for your affected file. I pushed a probable fix that should catch this error as well, can you please update the extension and tell me if it helped you?

**Comment by faustoserone** [comment]
unfortunately it doesn't work, but it seems to have changed the error report slightly:

*** Error loading script: tag_autocomplete_helper.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 539, in <module>
        write_temp_files()
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 509, in write_temp_files
        get_yaml_wildcards()
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 187, in get_yaml_wildcards
        parse_dynamic_prompt_format(yaml_wildcards, data, path)
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 163, in parse_dynamic_prompt_format
        recurse_dict(data)
      File "G:\stable-diffusion-webui\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py", line 157, in recurse_dict
        for key, value in d.copy().items():
    AttributeError: 'list' object has no attribute 'items'

**Comment by faustoserone** [comment]
I removed all the YAML files and it works.

**Comment by DominikDoom** [comment]
Ah I see, now it's the other YAML format that breaks. I pushed another fix, that should really cover all YAML file problems.
You can put the files back and it should log which file was the issue now.

**Comment by faustoserone** [comment]
No error log. Now it works! Thank you very much <3
