### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by R-N** [DominikDoom/a1111-sd-webui-tagcomplete#69]
<details><summary>error trace</summary>

```
Error loading script: dataset_tag_editor_ui.py
Traceback (most recent call last):
  File "/content/nai/stable-diffusion-webui/modules/scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "/content/nai/stable-diffusion-webui/extensions/stable-diffusion-webui-dataset-tag-editor/scripts/dataset_tag_editor_ui.py", line 6, in <module>
    from dataset_tag_editor import DatasetTagEditor
  File "/content/nai/stable-diffusion-webui/extensions/stable-diffusion-webui-dataset-tag-editor/dataset_tag_editor.py", line 9, in <module>
    def get_filepath_set(dir: str, recursive: bool) -> set[str]:
TypeError: 'type' object is not subscriptable
```
</details>

Environment: Google colab
Webui latest commit: 804d9fb83d0c63ca3acd36378707ce47b8f12599
Tag complete latest commit: 2d45d6c796d8dc4ef04b375998a599a2a0a53273

**Comment by R-N** [comment]
My bad. Wrong repo
