### ISSUE TITLE
[Bug] Can't Upgrade from Legacy to Extension version

### ISSUE THREAD

**Issue by mnielsendev** [DominikDoom/a1111-sd-webui-tagcomplete#76]
I had been using the script version until today when I went to update and found there was an extension version. I went ahead and installed the extension via git clone into WebUI dir/extensions/tag-autocomplete. Then I deleted the old files from the legacy version including tag_autocomplete_helper.py from WebUI dir/scripts as well as the WebUI dir/tags folder.

I figured that since the contents of those file now exist in the extensions version, everything should work just fine. Unfortunately, when I started the WebUI, I got an series of errors regarding the old legacy files I deleted (see below). It seems that the WebUI really wants to use the legacy version instead of the extension and I have no idea why. I'd prefer to use the extension if possible.

The error seems to suggest that because the contents of the old WebUI dir/tags folder are now gone, it cannot operate. I tried deleting the venv folder (since it appears the errors have to do with some packages in venv) and regenerated it, but that did nothing to fix the errors. I also checked WebUI dir/tmp tagAutocompletePath.txt and it is indeed listed correctly `extensions/tag-autocomplete/tags` so that doesn't seem to be the cause.

Any ideas?

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI\\Diffusion\\Stable Diffusion WebUI\\tags\\config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path D:\AI\Diffusion\Stable Diffusion WebUI\tags\config.json does not exist.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 331, in __call__
    stat_result = await anyio.to_thread.run_sync(os.stat, self.path)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\AI\\Diffusion\\Stable Diffusion WebUI\\tags\\temp\\emb.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "D:\AI\Diffusion\Stable Diffusion WebUI\venv\lib\site-packages\starlette\responses.py", line 334, in __call__
    raise RuntimeError(f"File at path {self.path} does not exist.")
RuntimeError: File at path D:\AI\Diffusion\Stable Diffusion WebUI\tags\temp\emb.txt does not exist.
```

Additional info: Windows 10, 24GB VRAM, 16GB RAM, Python 3.10.6, local Gradio ver WebUI

**Comment by DominikDoom** [comment]
Did you also delete the javascript part (`javascript/tagAutocomplete.js`)? That's the main part of this script, so it might search in the wrong place because of that if that still is left from the old version.

**Comment by mnielsendev** [comment]
> Did you also delete the javascript part (`javascript/tagAutocomplete.js`)? That's the main part of this script, so it might search in the wrong place because of that if that still is left from the old version.

That was the cause! I forgot about the javascript file. Thank you so much! And for the quick response too!
