### ISSUE TITLE
Can't install on TheLastBen Fast Stable Diffusion Collab

### ISSUE THREAD

**Issue by nikleonard** [DominikDoom/a1111-sd-webui-tagcomplete#79]
Attempting to install in Fast Stable Diffusion collab fails with the following path related error:
Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 77, in <module>
    write_tag_base_path()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 63, in write_tag_base_path
    f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())
  File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stable-diffusion'

**Comment by DominikDoom** [comment]
This is because the colab has a non-default working directory, as far as I'm aware I can't account for that on my side. But you can edit the colab code so it points at the needed place, see #67.
